'use client';

import { useEffect } from 'react';
import { globalAudioCache } from '@/services/voice/audioCache';
import { V6_STATIC_AUDIO_TEXTS } from '@/lib/v6/static-audio-texts';

/**
 * V6 Audio Preloader - Static File Version (Multi-Voice Support)
 * 
 * Preloads all static audio segments for v6 treatment sessions from pre-generated files.
 * This eliminates the need for TTS API calls, reducing costs to $0.
 * 
 * How it works:
 * 1. Audio files are pre-generated once per voice using scripts/generate-static-audio.js
 * 2. Files are stored in public/audio/v6/static/[voice-name]/
 * 3. This component loads the manifest for the selected voice and preloads the files
 * 4. Users download static MP3 files (no API calls = no cost)
 * 
 * Cost: $0 per user (vs ~10,000 credits per user with dynamic generation)
 */

// Manifest will be loaded from public/audio/v6/static/[voice]/manifest.json
// Generated by scripts/generate-static-audio.js [voice-name]
type AudioManifestEntry = {
  filename?: string;
  hash: string;
  path?: string;
  formats?: Record<string, {
    filename: string;
    path: string;
    mime?: string;
  }>;
};

type AudioManifest = {
  [key: string]: AudioManifestEntry;
};

interface V6AudioPreloaderProps {
  voice?: string; // 'heart' | 'michael' etc.
}

export default function V6AudioPreloader({ voice = 'heart' }: V6AudioPreloaderProps) {
  useEffect(() => {
    const userAgent = typeof navigator !== 'undefined' ? navigator.userAgent : '';
    const isIOSClient =
      /iPhone|iPad|iPod/i.test(userAgent) ||
      (/Macintosh/i.test(userAgent) && /Mobile/i.test(userAgent));

    const preloadStaticAudio = async () => {
      let successCount = 0;
      let skipCount = 0;
      let failCount = 0;
      const selectedFormatsCount: Record<string, number> = {};

      const normalizeAudioBlobType = (blob: Blob, selectedFormat?: string): Blob => {
        if (selectedFormat === 'wav') {
          return blob.slice(0, blob.size, 'audio/wav');
        }

        const unsupportedOrGenericType = !blob.type ||
          blob.type === 'audio/opus' ||
          blob.type === 'application/opus' ||
          blob.type === 'application/octet-stream';

        if (!unsupportedOrGenericType) {
          return blob;
        }

        return blob.slice(0, blob.size, 'audio/ogg; codecs=opus');
      };

      const chooseBestFormat = (entry: AudioManifestEntry): { format: string; path: string; filename: string } | null => {
        const formats = entry.formats || {};
        const audioProbe = typeof Audio !== 'undefined' ? new Audio() : null;
        const supportsOggOpus = Boolean(audioProbe?.canPlayType('audio/ogg; codecs=opus'));
        const supportsWav = Boolean(audioProbe?.canPlayType('audio/wav'));

        const orderedCandidates = isIOSClient
          ? ['wav', 'opus']
          : supportsOggOpus
            ? ['opus', 'wav']
            : supportsWav
              ? ['wav', 'opus']
              : ['opus', 'wav'];

        for (const candidate of orderedCandidates) {
          const info = formats[candidate];
          if (info?.path) {
            return { format: candidate, path: info.path, filename: info.filename };
          }
        }

        if (entry.path && entry.filename) {
          return { format: 'legacy', path: entry.path, filename: entry.filename };
        }

        return null;
      };

      console.log(`🎵 V6: Starting audio preload for voice "${voice}" from static files...`);

      try {
        // Load the manifest for the selected voice
        const manifestResponse = await fetch(`/audio/v6/static/${voice}/manifest.json`);
        
        if (!manifestResponse.ok) {
          console.error(`❌ Static audio manifest not found for voice "${voice}". Audio preloading disabled.`);
          console.error('   To fix this:');
          console.error(`   1. Run: node scripts/generate-static-audio.js ${voice}`);
          console.error('   2. Commit the generated files');
          console.error('   3. Redeploy');
          // No fallback to dynamic TTS - prevents accidental API charges
          return;
        }

        const manifest: AudioManifest = await manifestResponse.json();
        const manifestKeys = Object.keys(manifest);

        console.log(`📋 Loaded manifest for "${voice}" with ${manifestKeys.length} audio files`);

        // Preload each audio file (skip INITIAL_WELCOME - it's short enough to generate on-demand)
        for (const [key, audioInfo] of Object.entries(manifest)) {
          // Skip INITIAL_WELCOME to save initial load time (it's now very short)
          if (key === 'INITIAL_WELCOME') {
            skipCount++;
            console.log(`   ⏭️  Skipped: INITIAL_WELCOME (will generate on-demand if needed)`);
            continue;
          }

          const text = V6_STATIC_AUDIO_TEXTS[key as keyof typeof V6_STATIC_AUDIO_TEXTS];
          
          if (!text) {
            console.warn(`⚠️ Unknown key in manifest: ${key}`);
            continue;
          }

          // Use voice-prefixed cache key to support multiple voices
          const cacheKey = `${voice}:${text}`;

          // Skip if already in cache
          if (globalAudioCache.has(cacheKey)) {
            skipCount++;
            continue;
          }

          try {
            const selected = chooseBestFormat(audioInfo);
            if (!selected) {
              throw new Error(`No compatible format found for key "${key}"`);
            }

            // Fetch the selected static audio file
            const audioResponse = await fetch(selected.path);
            
            if (!audioResponse.ok) {
              throw new Error(`Failed to load ${selected.filename}: ${audioResponse.status}`);
            }

            const audioBlob = normalizeAudioBlobType(await audioResponse.blob(), selected.format);
            const audioUrl = URL.createObjectURL(audioBlob);
            globalAudioCache.set(cacheKey, audioUrl);
            successCount++;
            selectedFormatsCount[selected.format] = (selectedFormatsCount[selected.format] || 0) + 1;
            
            // Log preview of what was cached
            const preview = text.substring(0, 50).replace(/\n/g, ' ');
            const ellipsis = text.length > 50 ? '...' : '';
            console.log(`   ✓ Cached: "${preview}${ellipsis}"`);
          } catch (err) {
            failCount++;
            const preview = text.substring(0, 50).replace(/\n/g, ' ');
            console.error(`   ✗ Failed: "${preview}..."`, err);
          }
        }

        console.log(`✅ V6 Audio preload complete for "${voice}"!`);
        console.log(`   Successfully cached: ${successCount} segment(s)`);
        console.log(`   Already cached: ${skipCount} segment(s)`);
        console.log(`   Failed: ${failCount} segment(s)`);
        console.log(`   Selected formats:`, selectedFormatsCount);
        console.log(`   Total cache size: ${globalAudioCache.size()} audio file(s)`);
        console.log(`   💰 Cost: $0 (using static files)`);
      } catch (err) {
        console.error('❌ Failed to load audio manifest:', err);
        console.error('   Audio preloading disabled - no dynamic TTS fallback (prevents charges)');
        // No fallback to dynamic TTS - prevents accidental API charges
      }
    };

    // Start preloading (static files only - no API fallback)
    // Note: Using voice-prefixed cache keys allows multiple voices to be cached simultaneously
    preloadStaticAudio();
  }, [voice]); // Re-run when voice changes

  // This component doesn't render anything
  return null;
}
